import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import os

### Enter streamlit run ./src/dashboard.py in Terminal to launch the dashboard

# --- 1. Basic Page Configuration ---
# Removed the 'page_icon' argument to remove the chart icon from the browser tab
st.set_page_config(page_title="Smart Inventory Optimization System", layout="wide")

st.title("End-to-End Inventory Optimization System")
st.markdown("### Based on LightGBM Quantile Regression & Dynamic Newsvendor Model")

# --- 2. Load Data (Using cache for acceleration) ---
@st.cache_data
def load_data():
    # Load the prediction results generated by train_model.py
    # Ensure this path is correct relative to where you run the 'streamlit run' command.
    # Based on your screenshot, running from root, this path is correct:

    current_dir = os.path.dirname(os.path.abspath(__file__))
    processed_data_path = os.path.join(os.path.dirname(current_dir), 'data', 'processed')
    path = os.path.join(processed_data_path, 'm5_predictions.parquet')

    df = pd.read_parquet(path)
    # Ensure correct date format
    df['date'] = pd.to_datetime(df['date'])
    df = df.dropna(subset=['sales', 'sell_price', 'pred_q50', 'pred_q90'])
    return df

try:
    df_all = load_data()
except Exception as e:
    # English error message
    st.error(f"Data loading failed. Please check if the path is correct: {e}")
    st.stop()

# --- 3. Sidebar: Control Panel ---
st.sidebar.header("Simulation Control Panel")

# Select Product
unique_items = df_all['item_id'].unique()
selected_item = st.sidebar.selectbox(label="Select a product for analysis:", options=unique_items)

st.sidebar.markdown("---")
st.sidebar.subheader("Financial Parameter Settings")
# Interactive sliders: Let users define customized business parameters
# Labels changed to pure English
margin = st.sidebar.slider("Gross Margin", 0.05, 0.60, 0.25, 0.01)
annual_holding_rate = st.sidebar.slider("Annual Holding Cost Rate", 0.1, 0.5, 0.25, 0.05)
daily_spoilage_rate = st.sidebar.slider("Daily Spoilage Rate", 0.0, 0.05, 0.01, 0.001)

# Calculate derived parameters
daily_holding_rate = annual_holding_rate / 365

# --- 4. Core Logic: Single Product Real-time Backtesting Engine ---
# Filter data for the currently selected product
df = df_all[df_all['item_id'] == selected_item].sort_values('date').reset_index(drop=True).copy()

# Dynamically calculate costs (based on user slider input for margin)
df['cost'] = df['sell_price'] * (1 - margin)
df['daily_holding_unit_cost'] = df['cost'] * daily_holding_rate


def run_simulation(data, policy_col):
    """
    Runs a real-time inventory simulation and returns detailed daily flow records.
    """
    profit_list = []
    inventory_list = []
    stockout_count = 0
    current_inventory = 0.0

    for idx, row in data.iterrows():
        # 1. Replenishment
        target = np.ceil(row[policy_col])
        order_qty = max(0, target - current_inventory)
        stock_available = current_inventory + order_qty

        # 2. Sales
        demand = row['sales']
        sales = min(stock_available, demand)

        if demand > stock_available:
            stockout_count += 1

        # 3. Settlement and Spoilage
        unsold = stock_available - sales
        spoilage = unsold * daily_spoilage_rate
        current_inventory = unsold - spoilage  # Carry over to tomorrow

        # 4. Financial Calculation
        revenue = sales * row['sell_price']
        cogs = sales * row['cost']
        holding = unsold * row['daily_holding_unit_cost']
        spoil_cost = spoilage * row['cost']

        daily_net_profit = revenue - cogs - holding - spoil_cost

        profit_list.append(daily_net_profit)
        inventory_list.append(stock_available) # Record peak inventory level of the day

    return profit_list, inventory_list, stockout_count

# Run both strategies
profits_q50, inv_q50, out_q50 = run_simulation(df, policy_col='pred_q50')
profits_q90, inv_q90, out_q90 = run_simulation(df, policy_col='pred_q90')

# Write results back to DataFrame for plotting
df['cum_profit_q50'] = np.cumsum(profits_q50)
df['cum_profit_q90'] = np.cumsum(profits_q90)
df['inv_q90'] = inv_q90  # We focus on plotting P90 inventory changes

# --- 5. Visualization Presentation Layer ---

# A. Top Level KPI Scorecards
total_profit_q50 = sum(profits_q50)
total_profit_q90 = sum(profits_q90)
uplift = (total_profit_q90 - total_profit_q50) / abs(total_profit_q50) * 100
sl_q90 = (1 - out_q90 / len(df)) * 100

col1, col2, col3, col4 = st.columns(4)
# English labels for metrics
col1.metric(label="Strategy A (P50) Total Profit", value=f"${total_profit_q50:,.0f}")
col2.metric(label="Strategy B (P90) Total Profit", value=f"${total_profit_q90:,.0f}", delta=f"{uplift:.1f}%")
col3.metric(label="Strategy B In-stock Rate", value=f"{sl_q90:.1f}%")
col4.metric(label="Simulation Days", value=f"{len(df)} Days")

# B. Chart: Cumulative Profit Comparison
st.subheader("Cumulative Profit Trend Comparison")
fig_profit = go.Figure()
fig_profit.add_trace(go.Scatter(x=df['date'], y=df['cum_profit_q50'], mode='lines', name='Strategy A (P50)',
                                line=dict(color='gray', dash='dash')))
fig_profit.add_trace(go.Scatter(x=df['date'], y=df['cum_profit_q90'], mode='lines', name='Strategy B (P90)',
                                line=dict(color='green', width=3)))
# English axis titles
fig_profit.update_layout(xaxis_title="Date", yaxis_title="Cumulative Net Profit ($)", hovermode="x unified")
st.plotly_chart(fig_profit, use_container_width=True)

# C. Chart: Inventory vs Sales Detail
st.subheader("Inventory Level vs Actual Demand")
fig_inv = go.Figure()
# Plot actual sales (Bar chart)
fig_inv.add_trace(go.Bar(x=df['date'], y=df['sales'], name='Actual Customer Demand', marker_color='orange'))
# Plot P90 inventory level (Area chart)
fig_inv.add_trace(
    go.Scatter(x=df['date'], y=df['inv_q90'], name='P90 Dynamic Inventory Level', fill='tozeroy', line=dict(color='#00CC96')))
# Plot P50 forecast (Reference line)
fig_inv.add_trace(go.Scatter(x=df['date'], y=df['pred_q50'], name='P50 Forecast (Traditional)', line=dict(color='gray', dash='dot')))

# English axis titles; "Quantity (Units)" instead of "数量 (个)"
fig_inv.update_layout(xaxis_title="Date", yaxis_title="Quantity (Units)", hovermode="x unified")
st.plotly_chart(fig_inv, use_container_width=True)

# D. Data Details Table
# English expander label
with st.expander("View Detailed Data Report"):
    st.dataframe(df[['date', 'sales', 'pred_q50', 'pred_q90', 'inv_q90', 'cum_profit_q90']].style.format("{:.2f}", subset=['pred_q50', 'pred_q90', 'inv_q90', 'cum_profit_q90']))